### ISSUE TITLE
Add Metrics and Simple Baselines

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/ocf-ml-metrics#1]
We should have standard metrics and very simple baselines for use in training our models. 

Baseline Models:
- [x] All 0's
- [x] All max capacity
- [x] Last-value persistence
- [ ] Last-day persistence (copy the last day as the next days forecast)
- [ ] PV Live intraday

Metrics:
- [x] NMAE
- [x] Error during morning, afternoon, and evening
- [x] Error across different time horizons
- [x] Error in different Winter, Spring, Summer, Fall
- [x] RMSE
- [x] MAE
- [x] Count of errors larger than 1 and 2 GigaWatts option
- [x] Option to keep night time data, or remove it ( defined by sun angle)
- [ ] % of errors above 1.65 sigma, with sigma being the standard deviation of the outturn

**Comment by peterdudfield** [comment]
Good use of 'transfer' feature

**Comment by dantravers** [comment]
Sounds good!  Another "model" I would run is to compare against is PV_Live intraday versus PV_Live updated.  This gives an estimate of accuracy for national and GSP that we know we want to beat. 

To generalise the "large errors" - for National I think this is good to look at errors > 1GW (or maybe 2GW).  For site level or GSP level, I would apply a statistical measure.  Propose to count the % of errors which are greater than 1.65*sigma, where sigma is the standard deviation of the timeseries of outturns.  1.65*sigma equates to the 5 / 95% range of outturns for the site.
Could be any threshold, but this is probably as good as any.

**Comment by peterdudfield** [comment]
We avtaully have a few years worth, Jame re run some things. 

I would suggestion we use Plive intraday as another baseline mode, rather than intagle each model with PV Live intraday. That make sense?

**Comment by peterdudfield** [comment]
> Sounds good! Another "model" I would run is to compare against is PV_Live intraday versus PV_Live updated. This gives an estimate of accuracy for national and GSP that we know we want to beat.
> 
> To generalise the "large errors" - for National I think this is good to look at errors > 1GW (or maybe 2GW). For site level or GSP level, I would apply a statistical measure. Propose to count the % of errors which are greater than 1.65_sigma, where sigma is the standard deviation of the timeseries of outturns. 1.65_sigma equates to the 5 / 95% range of outturns for the site. Could be any threshold, but this is probably as good as any.

Perhaps a straigh forward threshol could be v0, then for v1 we could look at something a bit more eloborate

**Comment by jacobbieker** [comment]
Yeah, that's what I was thinking for the model. We can compute the errors and save those too if we want to, but would do that later. Comparing to the day after PV Live is already what the other error metrics do so don't think we need to include that separately. Is the intraday saved somewhere in a file?

> I would suggestion we use Plive intraday as another baseline mode, rather than intagle each model with PV Live intraday. That make sense?

**Comment by dantravers** [comment]
> * [x]  NMAE
>         
>       
>   
>       Create an issue with the title NMAE. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  Error during morning, afternoon, and evening
>         
>       
>   
>       Create an issue with the title Error during morning, afternoon, and evening. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  Error across different time horizons
>         
>       
>   
>       Create an issue with the title Error across different time horizons. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  Error in different Winter, Spring, Summer, Fall
>         
>       
>   
>       Create an issue with the title Error in different Winter, Spring, Summer, Fall. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  RMSE
>         
>       
>   
>       Create an issue with the title RMSE. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  MAE
>         
>       
>   
>       Create an issue with the title MAE. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  Count of errors larger than 1 and 2 GigaWatts option
>         
>       
>   
>       Create an issue with the title Count of errors larger than 1 and 2 GigaWatts option. Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [x]  Option to keep night time data, or remove it ( defined by sun angle)
>         
>       
>   
>       Create an issue with the title Option to keep night time data, or remove it ( defined by sun angle). Press Enter to convert to an issue instantly. Press Alt-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  % of errors above 1.65 sigma, with sigma being the standard deviation of the outturn

Thinking about this further - I would simplify and make the large errors anything above a % of the capacity for that region / site.  E.g. 10% of installed capacity.

**Comment by dantravers** [comment]
I would suggest the following metrics are the "headline" metrics that we use to compare models at the first pass, and then look at others for more detail: 
* nMAE
* split by forecast horizon
For national forecasts:
 * % errors > 1GW
 * MAE (although doesn't provide more information than nMAE, it is humanly understood)
 * split by forecast horizon.
For site-level forecasts: 
* % errors > 10% of installed capacity (large errors - an equivalent of the 1GW for national)
